[package]
name = "error-context-macro"
version = "0.1.0"
edition = "2024"
authors = ["Joey Ezechiëls"]
license = "MIT"
rust-version = "1.86.0"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.100", features = ["extra-traits"] }

[lib]
proc-macro = true
